version: '3.4'

services:
  backend:
    container_name: backend
    restart: always
    depends_on: 
      - db
    build: 
      context: .
      dockerfile: /backend/Dockerfile
    ports:
      - '7000:80'
  
  client:
    container_name: client
    build: /frontend
    ports:
      - '3000:80'
    depends_on:
      - backend
    restart: always
      
  db:
    container_name: pgdb
    image: postgres
    environment:
      POSTGRES_PASSWORD: 475269
      POSTGRES_USER: admin
      POSTGRES_DB: NoruBanner
    restart: always
    volumes:
      - mypgsql_data:/var/lib/postgresql/data
    ports:
      - '5432'
      
  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
  
volumes:
  mypgsql_data:
